### ISSUE TITLE
add HF dataset loading script for the Argumentative Microtext Corpus

### ISSUE THREAD

**Issue by ArneBinder** [ArneBinder/pie-document-level#86]
# General Dataset Infos
- website: http://angcl.ling.uni-potsdam.de/resources/argmicro.html
- paper: 
	- Andreas Peldszus and Manfred Stede. An annotated corpus of argumentative microtexts. In D. Mohammed, and M. Lewinski, editors, Argumentation and Reasoned Action - Proc. of the 1st European Conference on Argumentation, Lisbon, 2015. College Publications, London, 2016
	- preprint: https://peldszus.github.io/files/eca2015-preprint.pdf

# Tasks
- [x] understand the dataset: 
    - what is the base data? i.e. what kind of texts?
    - how was it annotated?
    - what label sets? e.g. for units and relations
 - [x] understand Huggingface dataset loading scripts
   - what is the `datasets` library? How is it used? advantages?
   - walk through the tutorial: https://huggingface.co/docs/datasets/dataset_script
   - understand an example, e.g. https://huggingface.co/datasets/conll2003/blob/main/conll2003.py
 - [x] create a dataset loading script for the corpus called `argumentative_microtext_corpus`
   - define the data structure (`features`): Stay as close as possible to the original data. Any (pre-)processing may be model specific and should happen outside / after the dataset loading script! 
   - define a config class and add individual configs for all dataset variants (e.g. languages)
   - implement the data loading and split generation (`_split_generators`)
   - implement the example generation (`_generate_examples`)
   - test it
