### ISSUE TITLE
add pie dataset loading script for SciDTB corpus

### ISSUE THREAD

**Issue by jk-tripathy** [ArneBinder/pie-document-level#98]
### General Dataset Info

- Citation: An Yang and Sujian Li. 2018. SciDTB: Discourse Dependency TreeBank for Scientific Abstracts. In Proceedings of the 56th Annual Meeting of the Association for Computational Linguistics (Volume 2: Short Papers), pages 444–449, Melbourne, Australia. Association for Computational Linguistics.
- [ACL Link](https://aclanthology.org/P18-2071/)
- [Dataset Github](https://github.com/PKU-TANGENT/SciDTB)

### Tasks

- [ ] Understand the structure of the data
- [ ] Create SciDTBDocument
- [ ] Create example_to_document and document_to_example. EDIT: See dataset builders at https://huggingface.co/pie for examples
- [ ] Extend pytorch_ie.data.builder.GeneratorBasedBuilder for SciDTB class
- [ ] Test it
